version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_db
    volumes:
      - ${MYSQL_DATA_DIR-./db}:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  joomla:
    depends_on:
      - db
    image: joomla:latest
    container_name: ${PROJECT_NAME}_srv
    ports:
      - ${JOOM_HOST_MACHINE_PORT-8000}:80
    restart: always
    environment:
      JOOMLA_DB_HOST: ${JOOM_DB_HOST}
      JOOMLA_DB_NAME: ${JOOM_DB_NAME}
      JOOMLA_DB_USER: ${JOOM_DB_USER}
      JOOMLA_DB_PASSWORD: ${JOOM_DB_PASS}
    volumes:
      - ${JOOM_DATA_DIR-./joomla}:/var/www/html

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: ${PROJECT_NAME}_pma
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    restart: always
    ports:
      - ${PMA_HOST_MACHINE_PORT-8080}:80
    volumes:
      - /sessions